### ISSUE TITLE
Hey, having troubles.

### ISSUE THREAD

**Issue by YachyGit** [DrOreo002/GrowtopiaJavaBot#2]
Oreo, maybe u have discord?

**Comment by DrOreo002** [comment]
Just talk here, discord is laggy on me

**Comment by YachyGit** [comment]
> Just talk here, discord is laggy on me

I wanted to ask or u making any bot for currency (money)

**Comment by DrOreo002** [comment]
> > Just talk here, discord is laggy on me
> 
> I wanted to ask or u making any bot for currency (money)

The code is not from me. I "take" it from Growtopia Noobs's. So I do not have the rights to sell it. Ik it made with Java but still, its not 100% from me
